name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      ###
      # Checkout using GitHub's checkout action
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      ###
      # Setup Ruby - this needs to match the version in the Gemfile
      - name: Set up Ruby
        uses: ruby/setup-ruby@161cd54b698f1fb3ea539faab2e036d409550e3c
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      # Run the tests
      - name: Run Ruby tests
        env:
          EXERCISM_ENV: test
          EXERCISM_CI: true

        run: |
          bundle exec rake test
