name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      ###
      # Checkout using GitHub's checkout action
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      ###
      # Setup Ruby - this needs to match the version in the Gemfile
      - name: Set up Ruby
        uses: ruby/setup-ruby@1198b074305f9356bd56dd4b311757cc0dab2f1c
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      # Run the tests
      - name: Run Ruby tests
        env:
          EXERCISM_ENV: test
          EXERCISM_CI: true

        run: |
          bundle exec rake test
