name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      ###
      # Checkout using GitHub's checkout action
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938

      ###
      # Setup Ruby - this needs to match the version in the Gemfile
      - name: Set up Ruby
        uses: ruby/setup-ruby@50ba3386b050ad5b97a41fcb81240cbee1d1821f
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      # Run the tests
      - name: Run Ruby tests
        env:
          EXERCISM_ENV: test
          EXERCISM_CI: true

        run: |
          bundle exec rake test
